### ISSUE TITLE
Error 503 in response from HTTP POST

### ISSUE THREAD

**Issue by yennster** [dreamfactorysoftware/df-managed#2]
Hi, I am at a loss as to why I am unable to POST successfully to my Dream Factory instance. I am able to send a curl from command-line successfully and receive the correct response, but when I format the data as a regular HTTP POST request and try to POST from my microcontroller C code, I get a 503 error. It looks like the error is from the [ClusterService.php](https://github.com/dreamfactorysoftware/df-managed/blob/master/src/Services/ClusterService.php) file. Any thoughts?

Here's my successful curl (with authorization information redacted):
```
curl -X POST "https://<redacted>.dreamfactory.com/api/v2/testdb/_table/Measurements" -H "Content-Type: application/json" -H "accept: application/json"  -H "X-DreamFactory-API-Key: <redacted>" -d "{\"resource\":[{\"userID\":1,\"weight\":1,\"timestamp\":\"2018-02-17 21:05:13.5096722\",\"productID\":2,\"created_date\":\"2018-02-07 21:05:13.5096722\",\"last_updated_date\":\"2018-02-07 21:05:13.5096722\"}]}"
```

Curl successful response:
```
{"resource":[{"measurementID":21}]}
```

And here's my unsuccessful HTTP POST request as used in my esp32 microcontroller code:
```
POST https://<redacted>.dreamfactory.com/api/v2/testdb/_table/Measurements HTTP/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json
X-DreamFactory-API-Key: <redacted>
{"resource":[{"userID":1,"weight":32,"timestamp":"2018-01-02 00:00:00.00","productID":2,"created_date":"2018-01-01 00:00:00.00","last_updated_date":"2018-01-01 00:00:00.00"}]}
```

MCU error response:
```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, private
Date: Wed, 28 Feb 2018 18:28:55 GMT
x-dreamfactory-routed: true

{"error":{"code":503,"message":"Error interrogating console: Corrupt response during status query for \"\"."}}
```

I did a google search for "Error interrogating console" and I was directed to this GitHub repository. Any guidance would be very much appreciated!

**Comment by todda48** [comment]
It looks like there is a low-level problem with your DreamFactory instance you created on the free hosted system. See if you can do a GET on /api/v2 for your instance. If this doesn't work I'd suggest trying it on a new instance. Keep in mind the free hosted instances only last for 30 days.

**Comment by yennster** [comment]
@todda48 I can do a curl GET just fine with URL authorization:
```
curl -X GET "https://<redacted>.dreamfactory.com/api/v2/testdb/_table/Measurements" -H "Content-Type: application/json" -H "accept: application/json"  -H "X-DreamFactory-API-Key: <redacted>" 
```

But I still get the `{"error":{"code":503,"message":"Error interrogating console: Corrupt response during status query for \"\"."}}` response when I use a similar HTTP GET on the MCU.

We only made the free DreamFactory instance about a week ago as well, hmmm...

**Comment by yennster** [comment]
I can also do a curl GET request on /api/v2 successfully with:
```
curl -X GET "https://<redacted>.dreamfactory.com/api/v2/" -H "Content-Type: application/json" -H "accept: application/json"  -H "X-DreamFactory-API-Key: <redacted>" 
```

**Comment by todda48** [comment]
Try POSTing your payload to requestbin or similar. Maybe that will reveal something different about cURL vs MCU requests.

**Comment by yennster** [comment]
@todda48 So I fixed my code and am now able to send the following request:
```
POST https://<redacted>.dreamfactory.com/api/v2/testdb/_table/Measurements HTTP/1.0
User-Agent: esp-idf/1.0 esp32
Connection: close
Host: <redacted>.oraclecloud2.dreamfactory.com
Authorization: <redacted>
Content-Type: application/json
X-DreamFactory-API-Key: <redacted>

{"resource":[{"userID":1,"weight":32,"timestamp":"2018-01-02 00:00:00.00","productID":2,"created_date":"2018-01-01 00:00:00.00","last_updated_date":"2018-01-01 00:00:00.00"},]}
```

But I'm getting the following error response: 
```
HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/json
Connection: close
Cache-Control: private, must-revalidate
Date: Sun, 04 Mar 2018 23:41:33 GMT
pragma: no-cache
expires: -1

{"error":{"code":400,"context":null,"message":"No record(s) detected in request. Please make sure record(s) are wrapped in a 'resource' tag. Example: {&quot;resource&quot;:[{&quot;record&quot;:1},{&quot;record&quot;:2}]}","status_code":400}}
```

I don't understand what is wrong with my JSON string:
```
{"resource":[{"userID":1,"weight":32,"timestamp":"2018-01-02 00:00:00.00","productID":2,"created_date":"2018-01-01 00:00:00.00","last_updated_date":"2018-01-01 00:00:00.00"}]}
```

**Comment by yennster** [comment]
@todda48 Thank you for your help by the way, I appreciate it

**Comment by todda48** [comment]
Sure, no problem. In the payload, if you are sending the comma at the end of the array that's not valid JSON. Hopefully that'll fix it.

**Comment by yennster** [comment]
@todda48 Removed the comma, same error. :( I'll try something else

**Comment by yennster** [comment]
This is my JSON string:
```
{"resource":[{"userID":1,"weight":32,"timestamp":"2018-01-02 00:00:00.00","productID":2,"created_date":"2018-01-01 00:00:00.00","last_updated_date":"2018-01-01 00:00:00.00"}]}
```

**Comment by todda48** [comment]
It looks correct. There is a test console in each instance you could try. Go to /test_rest.html for your DF instance. Fill out the form with your URL, payload, POST, and creds then click Submit.

![2018-03-05_14-03-22](https://user-images.githubusercontent.com/3788407/36994137-2387181e-207e-11e8-8011-595093bb7f32.png)

**Comment by yennster** [comment]
@todda48 Awesome, that's helpful to know. So I tried it using my URL, API key, and authorization header (basic authorization with base64 encoded username/password). And I received an error. 

```
{
	"error": {
		"code": 401,
		"context": null,
		"message": "Invalid token: Wrong number of segments",
		"status_code": 401
	}
}
```

However, the following works and I receive the correct response:
![POST request](https://gist.github.com/yennster/815893fc18bdfdbea24b4fec2df98932/raw/7be95f737236aeee91cabe59171e8ee65a4de104/post.png?raw=true)

Is there something wrong with Basic authorization? How does dreamfactory interpret the "HTTP auth" entries on that form?

**Comment by todda48** [comment]
You just have to enter the raw credentials and the form takes care of adding the Authorization header. If you are an admin user then API key doesn't matter.

```
if(username && password){
    xhr.setRequestHeader("Authorization", "Basic "+btoa(username+':'+password));
}
```
There has to be something different about the MCU request. Does it have special characters of some sort, like maybe curly quotes vs regular quotes?

**Comment by todda48** [comment]
'Authorization Header' is for bearer auth.  Use basic auth instead with username/password.

**Comment by yennster** [comment]
@todda48 Yeah I checked the curly quotes vs. regular quotes... Ugh I'll keep debugging

**Comment by todda48** [comment]
Could you give us screenshots of requestbin for MCU vs curl calls? Maybe we will see something.

**Comment by yennster** [comment]
@todda48 
Here's a dump from the MCU to PTSV2: http://ptsv2.com/t/zx7j8-1520289182/d/40001

![MCU](https://gist.github.com/yennster/815893fc18bdfdbea24b4fec2df98932/raw/7be95f737236aeee91cabe59171e8ee65a4de104/mcu-post.png?raw=true)

Here's a dump from curl to PTSV2: http://ptsv2.com/t/zx7j8-1520289182/d/240001

![curl](https://gist.github.com/yennster/815893fc18bdfdbea24b4fec2df98932/raw/7be95f737236aeee91cabe59171e8ee65a4de104/curl-post.png?raw=true)

**Comment by yennster** [comment]
@todda48 EUREKA 💡 
For some reason the "Content-Length: 90" header HAS to be present and the value HAS to be correct (I have no idea why).

The following POST works:
```
 POST https://<redacted>.oraclecloud2.dreamfactory.com/api/v2/testdb/_table/Measurements HTTP/1.1
User-Agent: esp-idf/1.0 esp32
Connection: close
Host: ft-hpeeler.oraclecloud2.dreamfactory.com
Authorization: Basic <redacted>
Content-Type: application/json
Content-Length: 90

{"resource":[{"userID":1,"weight":32,"timestamp":"2018-01-02 00:00:00.00","productID":2}]}
```

And I receive the following successful response:
```
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Cache-Control: no-cache, private
Date: Mon, 05 Mar 2018 22:59:38 GMT
x-dreamfactory-routed: true

24
{"resource":[{"measurementID":141}]}
0
```

Finally. Thank you so much for your help!

**Comment by todda48** [comment]
Glad you were able to figure it out!
